/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: RongstadJ (https://sketchfab.com/RongstadJ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koenigsegg-agera-rs-a30e098257254fcfa1323f2841e26d13
Title: Koenigsegg Agera RS
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Mat_FrontBrakePad} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Mat_FrontDiff} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Mat_FrontRim} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Mat_FrontTire} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Mat_FrontBrakeCaliper} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Mat_BackBrakeCaliper} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Mat_BackTire} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Mat_BackRim} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Mat_BackDiff} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Mat_BackBrakePad} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Mat_TaillightDetail} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Mat_RearDiffuse} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Mat_RearWings} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Mat_Spoiler} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Mat_HeadlightCover} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.Mat_Headlight} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Mat_FrontBumper} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.Mat_Door} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Mat_Roof} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Mat_BackMiddle} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Mat_BackBumper} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Mat_RearLight} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Mat_SideVent} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.Mat_FrontSideVent} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Mat_FrontVent} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.Mat_Frontventlarge} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.Mat_Mirror} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.Mat_FrontAirVent} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.Mat_Hood} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.Mat_BackAirVent} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.Mat_BackHalf} />
          <mesh geometry={nodes.defaultMaterial_31.geometry} material={materials.Mat_FrontSplitterLarge} />
          <mesh geometry={nodes.defaultMaterial_32.geometry} material={materials.Mat_FrontSplitter} />
          <mesh geometry={nodes.defaultMaterial_33.geometry} material={materials.Mat_CarBottom} />
          <mesh geometry={nodes.defaultMaterial_34.geometry} material={materials.Mat_Windshieldwiper} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
